### ISSUE TITLE
Can't Specify Management IP

### ISSUE THREAD

**Issue by skrtu** [RevengeComing/DemonHunter#1]
I think we should be able to specify the management IP as this will allow for running the C2 from the agent to management over a private network. I have created a fork of this.

I propose the following change to __init__.py under nodes, manager.

```
    def __init__(self, loop, server_address, agent_manager=True, web_app=None, agent_password=None, logfile=None):
        self.server_address = server_address
        self.loop = loop

        if agent_manager:
            if self.server_address is None:
                self.server_address = "127.0.0.1"
            coro = self.loop.create_server(lambda: AgentManager(self), self.server_address, 16742)
            server = self.loop.run_until_complete(coro)
            print('AgentManager Serving on {0}'.format(server.sockets[0].getsockname()))
            self.agent_password = agent_password
```
And then an update to the docs for manager.py

```
import asyncio
from demonhunter import Manager

loop = asyncio.get_event_loop()

# specify management IP via server_address
manager = Manager(loop, logfile='events.log', web_app=None, server_address=None)
manager.add_agent_address("107.170.73.18")

try:
    loop.run_forever()
except KeyboardInterrupt:
    print("\nServer Closed")

loop.close()
```

**Comment by RevengeComing** [comment]
you could change manager_address from "0.0.0.0" to the address you prefer. and i know the variable name was a little odd so i changed the code to how you suggested.

thanks for your contribution :+1: !

and also you can contribute on coding if you are interested. i don't do active development because i saw no interest around and i don't work as security software developer anymore. maybe i get some time to do more development.
